typography_spectrum: 0.43548386497423053
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38834531512111425
  lightness: 0.1884626941755414
  saturation: 0.8616814550478011
  rhythmicContrast: 0.5143162063322961
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.12343681696802378
analytics:
  google: null
  facebook: null
  twitter: null
name: 'HolaVecino '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Acerca de nosotros
    url: 'http://holavecino.ong/'
    type: external
favicon: null
title: Kit del Vecino Prendido
description: Como provocar tu barrio sin morir en el intento
purpose: []
